In [ ]:
# Machine Learning Model Building

## Objective

The objective of this notebook is to train, evaluate, and compare multiple machine learning models for disease prediction based on patient symptoms.

### Dataset Used

- dataset2_clean.csv

### Algorithms

- Decision Tree
- Random Forest

### Evaluation Metrics

- Accuracy
- Precision
- Recall
- F1-Score
- Confusion Matrix

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score

from sklearn.metrics import classification_report

from sklearn.metrics import confusion_matrix

In [3]:
dataset2 = pd.read_csv("../cleaned_datasets/dataset2_clean.csv")

In [4]:
dataset2.head()

,Disease,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,Panic Disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,Panic Disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Panic Disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Panic Disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,Panic Disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0


In [5]:
X = dataset2.drop("Disease", axis=1)

y = dataset2["Disease"]

In [6]:
print(X.shape)

print(y.shape)

(189647, 377)
(189647,)


In [7]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)

In [8]:
print(y.head())

0    Panic Disorder
1    Panic Disorder
2    Panic Disorder
3    Panic Disorder
4    Panic Disorder
Name: Disease, dtype: object


In [9]:
print(y_encoded[:10])

[531 531 531 531 531 531 531 531 531 531]


In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42
)

In [11]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (151717, 377)
X_test : (37930, 377)
y_train: (151717,)
y_test : (37930,)


In [12]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state=42)

decision_tree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [13]:
y_pred_dt = decision_tree.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score

dt_accuracy = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:", dt_accuracy)

Decision Tree Accuracy: 0.7548905879251252


In [15]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_dt))

C:\ProgramData\anaconda3\conda-meta\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\conda-meta\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


              precision    recall  f1-score   support

           0       0.27      0.60      0.38         5
           1       0.87      0.92      0.89        49
           2       0.39      0.66      0.49        29
           3       1.00      1.00      1.00         1
           4       0.41      0.76      0.54        25
           5       0.25      0.50      0.33         2
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         4
           8       0.46      0.63      0.53        82
           9       0.49      0.68      0.57       155
          10       0.83      0.91      0.87       238
          11       0.62      0.67      0.65       247
          12       0.51      0.64      0.57       166
          13       0.00      0.00      0.00         0
          14       0.11      0.23      0.15        30
          15       0.86      0.90      0.88       168
          16       0.57      0.60      0.59       108
          17       0.76    

C:\ProgramData\anaconda3\conda-meta\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\conda-meta\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\conda-meta\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", l

In [16]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_dt)

print(cm)

[[ 3  0  0 ...  0  0  0]
 [ 0 45  0 ...  0  0  0]
 [ 0  0 19 ...  0  0  0]
 ...
 [ 0  0  1 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0 53]]


In [ ]:
## Decision Tree Model - Observations

- The Decision Tree model was trained using the cleaned disease dataset.
- The dataset was split into 80% training and 20% testing.
- The model achieved an accuracy of approximately **75.5%**.
- The classification report shows strong performance for many diseases, while some rare diseases have lower precision and recall due to fewer training samples.
- The confusion matrix was generated to evaluate prediction performance across all disease classes.

In [ ]:
#Model Saving

In [18]:
import joblib

In [19]:
import os

os.makedirs("../saved_models", exist_ok=True)

print("Folder Ready!")

Folder Ready!


In [20]:
joblib.dump(decision_tree, "../saved_models/decision_tree_model.pkl")

print("Decision Tree Model Saved Successfully!")

Decision Tree Model Saved Successfully!


In [21]:
joblib.dump(label_encoder, "../saved_models/label_encoder.pkl")

print("Label Encoder Saved Successfully!")

Label Encoder Saved Successfully!


In [22]:
feature_names = X.columns.tolist()

joblib.dump(feature_names, "../saved_models/feature_names.pkl")

print("Feature Names Saved Successfully!")

Feature Names Saved Successfully!


In [23]:
os.listdir("../saved_models")

['decision_tree_model.pkl', 'feature_names.pkl', 'label_encoder.pkl']