In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [2]:
df = pd.read_csv("../processed_data/weighted_final_dataset.csv")

print(df.shape)
df.head()

(306, 133)


,prognosis,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
0,fungal infection,1,3,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,allergy,0,0,0,4,5,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,gerd,0,0,0,0,0,0,0,5,3,...,0,0,0,0,0,0,0,0,0,0
3,chronic cholestasis,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,drug reaction,1,3,0,0,0,0,0,5,0,...,0,0,0,0,0,0,0,0,0,0


In [3]:
# Features and Target

X = df.drop("prognosis", axis=1)
y = df["prognosis"]

print("Features:", X.shape)
print("Target:", y.shape)

Features: (306, 132)
Target: (306,)


In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training set:", X_train.shape)
print("Testing set :", X_test.shape)

Training set: (244, 132)
Testing set : (62, 132)


In [5]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

print("Random Forest trained successfully!")

Random Forest trained successfully!


In [6]:
y_pred = rf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 1.0


In [7]:
print(classification_report(y_test, y_pred))

                                         precision    recall  f1-score   support

(vertigo) paroymsal  positional vertigo       1.00      1.00      1.00         1
                                   acne       1.00      1.00      1.00         1
                                   aids       1.00      1.00      1.00         1
                    alcoholic hepatitis       1.00      1.00      1.00         2
                                allergy       1.00      1.00      1.00         1
                              arthritis       1.00      1.00      1.00         1
                                 asthma       1.00      1.00      1.00         1
                   cervical spondylosis       1.00      1.00      1.00         1
                             chickenpox       1.00      1.00      1.00         2
                    chronic cholestasis       1.00      1.00      1.00         2
                            common cold       1.00      1.00      1.00         2
                           

In [8]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 2]]


In [9]:
import joblib

joblib.dump(rf, "../models/random_forest_model.pkl")

print("✅ Model saved successfully!")

✅ Model saved successfully!


In [10]:
from xgboost import XGBClassifier



In [11]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(df["prognosis"])

In [12]:
print(y[:10])
print(type(y))

[15  4 17  9 14 34  2 12 16  6]
<class 'numpy.ndarray'>


In [13]:
X = df.drop("prognosis", axis=1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [14]:
print(y_train[:10])

[21 14 27  2 11 29 21 34 25 26]


In [15]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    objective="multi:softmax",
    eval_metric="mlogloss",
    n_estimators=300,
    max_depth=8,
    learning_rate=0.05,
    random_state=42
)

xgb.fit(X_train, y_train)

print("✅ XGBoost trained successfully!")

✅ XGBoost trained successfully!


In [16]:
y_pred_xgb = xgb.predict(X_test)

xgb_accuracy = accuracy_score(y_test, y_pred_xgb)

print("XGBoost Accuracy:", xgb_accuracy)

XGBoost Accuracy: 0.9032258064516129


In [17]:
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       0.50      1.00      0.67         1
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         1
           8       0.67      1.00      0.80         2
           9       0.33      0.50      0.40         2
          10       1.00      1.00      1.00         2
          11       1.00      1.00      1.00         2
          12       1.00      1.00      1.00         2
          13       1.00      1.00      1.00         1
          14       1.00      1.00      1.00         1
          15       0.00      0.00      0.00         1
          16       1.00      1.00      1.00         1
          17       1.00    

c:\Users\vishr\Downloads\MedAssist-AI\venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\vishr\Downloads\MedAssist-AI\venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\vishr\Downloads\MedAssist-AI\venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize

In [18]:
comparison = pd.DataFrame({
    "Model": ["Random Forest", "XGBoost"],
    "Accuracy": [accuracy, xgb_accuracy]
})

comparison

,Model,Accuracy
0,Random Forest,1.000000
1,XGBoost,0.903226


In [19]:
import joblib

joblib.dump(rf, "../models/best_model.pkl")

print("✅ Best model saved!")

✅ Best model saved!


In [20]:
joblib.dump(encoder, "../models/label_encoder.pkl")

print("✅ Label Encoder saved!")

✅ Label Encoder saved!
